### ISSUE TITLE
Invalid input | When you try to get meta

### ISSUE THREAD

**Issue by k1ll1n** [derhuerst/gulp-scale-images#28]
With this code, I get the error "Invalid input"
```
const readMetadata = require('gulp-scale-images/read-metadata')
const through = require('through2')
const scaleImages = require('gulp-scale-images')

const computeScaleInstructions = (file, _, cb) => {
	readMetadata(file.path, (err, meta) => {
		if (err) return cb(err)
		file = file.clone()
		file.scale = {
			maxWidth: Math.floor(meta.width / 2),
			maxHeight: Math.floor(meta.height / 2)
		}
		cb(null, file)
	})
}

gulp.src(…)
.pipe(through.obj(computeScaleInstructions))
.pipe(scaleImages())
.pipe(gulp.dest(…))
```

```
[14:25:15] Error: Invalid input
    at Sharp (/home/killin/WebstormProjects/akadem-klubb_2.0/node_modules/sharp/lib/constructor.js:158:11)
    at Object.readMetadata (/home/killin/WebstormProjects/akadem-klubb_2.0/node_modules/gulp-scale-images/read-metadata.js:6:2)
    at Transform.computeScaleInstructions [as _transform] (/home/killin/WebstormProjects/akadem-klubb_2.0/gulpfile.js:132:17)
    at Transform._read (/home/killin/WebstormProjects/akadem-klubb_2.0/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Transform._write (/home/killin/WebstormProjects/akadem-klubb_2.0/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/killin/WebstormProjects/akadem-klubb_2.0/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/killin/WebstormProjects/akadem-klubb_2.0/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Transform.Writable.write (/home/killin/WebstormProjects/akadem-klubb_2.0/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DestroyableTransform.ondata (/home/killin/WebstormProjects/akadem-klubb_2.0/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:315:20)

```

**Comment by derhuerst** [comment]
Please provide more details:

- your Node.js version, obtained via `node --version`
- the list of installed packages, e.g. obtained via `npm ls`
- a file (or [Vinyl object](https://gulpjs.com/docs/en/api/concepts#vinyl) to be exact) you're running the Gulp pipeline on

**Comment by hyvyys** [comment]
I'm getting this too so I'll chime in.

Node:
```
v14.16.0
```

[npm.ls.txt](https://github.com/derhuerst/gulp-scale-images/files/6815026/npm.ls.txt)

Happens with any image, so I'm not sure how the vinyl would help. And if that matters, I'm on macOS Big Sur.

**Comment by derhuerst** [comment]
I can run `example.js` within this repo just fine, using Node.js v14.17.3.

Have you double-checked that you're only sending *images* into `gulp-scale-images`? You can debug files in a Gulp pipeline using [`gulp-debug`](https://github.com/sindresorhus/gulp-debug).

**Comment by IAluI** [comment]
@derhuerst Hi! readme.md contains wrong example. The function [readMetadata](https://github.com/derhuerst/gulp-scale-images/blob/master/read-metadata.js) takes as its first argument Vinyl file instance. But in sample it take in first argement a string - `file.path`. Because of this people has this error.

**Comment by derhuerst** [comment]
Thanks @k1ll1n for reporting this, and thanks @IAluI for resolving this!
